/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FileType = IDL.Variant({
  'Insurance' : IDL.Null,
  'TestReport' : IDL.Null,
  'Xray' : IDL.Null,
  'DoctorNote' : IDL.Null,
  'Other' : IDL.Null,
  'Prescription' : IDL.Null,
});
export const MedicalRecordInput = IDL.Record({
  'visitDate' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : FileType,
  'notes' : IDL.Opt(IDL.Text),
  'hospitalName' : IDL.Text,
  'doctorName' : IDL.Text,
  'fileKey' : IDL.Text,
});
export const RecordId = IDL.Nat;
export const Timestamp = IDL.Int;
export const MedicalRecord = IDL.Record({
  'id' : RecordId,
  'visitDate' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : FileType,
  'notes' : IDL.Opt(IDL.Text),
  'hospitalName' : IDL.Text,
  'doctorName' : IDL.Text,
  'uploadedAt' : Timestamp,
  'fileKey' : IDL.Text,
});
export const UserId = IDL.Principal;
export const ProfileView = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'userId' : UserId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'emergencyContactPhone' : IDL.Text,
  'emergencyContactName' : IDL.Text,
});
export const ProfileInput = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'emergencyContactPhone' : IDL.Text,
  'emergencyContactName' : IDL.Text,
});

export const idlService = IDL.Service({
  'createMedicalRecord' : IDL.Func([MedicalRecordInput], [MedicalRecord], []),
  'deleteMedicalRecord' : IDL.Func([RecordId], [IDL.Bool], []),
  'getMyProfile' : IDL.Func([], [IDL.Opt(ProfileView)], []),
  'getMyRecord' : IDL.Func([RecordId], [IDL.Opt(MedicalRecord)], []),
  'listMyRecords' : IDL.Func([], [IDL.Vec(MedicalRecord)], []),
  'upsertMyProfile' : IDL.Func([ProfileInput], [ProfileView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FileType = IDL.Variant({
    'Insurance' : IDL.Null,
    'TestReport' : IDL.Null,
    'Xray' : IDL.Null,
    'DoctorNote' : IDL.Null,
    'Other' : IDL.Null,
    'Prescription' : IDL.Null,
  });
  const MedicalRecordInput = IDL.Record({
    'visitDate' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : FileType,
    'notes' : IDL.Opt(IDL.Text),
    'hospitalName' : IDL.Text,
    'doctorName' : IDL.Text,
    'fileKey' : IDL.Text,
  });
  const RecordId = IDL.Nat;
  const Timestamp = IDL.Int;
  const MedicalRecord = IDL.Record({
    'id' : RecordId,
    'visitDate' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : FileType,
    'notes' : IDL.Opt(IDL.Text),
    'hospitalName' : IDL.Text,
    'doctorName' : IDL.Text,
    'uploadedAt' : Timestamp,
    'fileKey' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const ProfileView = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'userId' : UserId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'emergencyContactPhone' : IDL.Text,
    'emergencyContactName' : IDL.Text,
  });
  const ProfileInput = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'emergencyContactPhone' : IDL.Text,
    'emergencyContactName' : IDL.Text,
  });
  
  return IDL.Service({
    'createMedicalRecord' : IDL.Func([MedicalRecordInput], [MedicalRecord], []),
    'deleteMedicalRecord' : IDL.Func([RecordId], [IDL.Bool], []),
    'getMyProfile' : IDL.Func([], [IDL.Opt(ProfileView)], []),
    'getMyRecord' : IDL.Func([RecordId], [IDL.Opt(MedicalRecord)], []),
    'listMyRecords' : IDL.Func([], [IDL.Vec(MedicalRecord)], []),
    'upsertMyProfile' : IDL.Func([ProfileInput], [ProfileView], []),
  });
};

export const init = ({ IDL }) => { return []; };