/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FileType = { 'Insurance' : null } |
  { 'TestReport' : null } |
  { 'Xray' : null } |
  { 'DoctorNote' : null } |
  { 'Other' : null } |
  { 'Prescription' : null };
export interface MedicalRecord {
  'id' : RecordId,
  'visitDate' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'fileType' : FileType,
  'notes' : [] | [string],
  'hospitalName' : string,
  'doctorName' : string,
  'uploadedAt' : Timestamp,
  'fileKey' : string,
}
export interface MedicalRecordInput {
  'visitDate' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'fileType' : FileType,
  'notes' : [] | [string],
  'hospitalName' : string,
  'doctorName' : string,
  'fileKey' : string,
}
export interface ProfileInput {
  'dateOfBirth' : string,
  'name' : string,
  'email' : string,
  'emergencyContactPhone' : string,
  'emergencyContactName' : string,
}
export interface ProfileView {
  'dateOfBirth' : string,
  'userId' : UserId,
  'name' : string,
  'email' : string,
  'updatedAt' : Timestamp,
  'emergencyContactPhone' : string,
  'emergencyContactName' : string,
}
export type RecordId = bigint;
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'createMedicalRecord' : ActorMethod<[MedicalRecordInput], MedicalRecord>,
  'deleteMedicalRecord' : ActorMethod<[RecordId], boolean>,
  'getMyProfile' : ActorMethod<[], [] | [ProfileView]>,
  'getMyRecord' : ActorMethod<[RecordId], [] | [MedicalRecord]>,
  'listMyRecords' : ActorMethod<[], Array<MedicalRecord>>,
  'upsertMyProfile' : ActorMethod<[ProfileInput], ProfileView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];