/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProfileView {
    dateOfBirth: string;
    userId: UserId;
    name: string;
    email: string;
    updatedAt: Timestamp;
    emergencyContactPhone: string;
    emergencyContactName: string;
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface MedicalRecord {
    id: RecordId;
    visitDate: string;
    fileName: string;
    fileSize: bigint;
    fileType: FileType;
    notes?: string;
    hospitalName: string;
    doctorName: string;
    uploadedAt: Timestamp;
    fileKey: string;
}
export interface MedicalRecordInput {
    visitDate: string;
    fileName: string;
    fileSize: bigint;
    fileType: FileType;
    notes?: string;
    hospitalName: string;
    doctorName: string;
    fileKey: string;
}
export interface ProfileInput {
    dateOfBirth: string;
    name: string;
    email: string;
    emergencyContactPhone: string;
    emergencyContactName: string;
}
export type RecordId = bigint;
export enum FileType {
    Insurance = "Insurance",
    TestReport = "TestReport",
    Xray = "Xray",
    DoctorNote = "DoctorNote",
    Other = "Other",
    Prescription = "Prescription"
}
export interface backendInterface {
    createMedicalRecord(input: MedicalRecordInput): Promise<MedicalRecord>;
    deleteMedicalRecord(recordId: RecordId): Promise<boolean>;
    getMyProfile(): Promise<ProfileView | null>;
    getMyRecord(recordId: RecordId): Promise<MedicalRecord | null>;
    listMyRecords(): Promise<Array<MedicalRecord>>;
    upsertMyProfile(input: ProfileInput): Promise<ProfileView>;
}
import type { FileType as _FileType, MedicalRecord as _MedicalRecord, MedicalRecordInput as _MedicalRecordInput, ProfileView as _ProfileView, RecordId as _RecordId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createMedicalRecord(arg0: MedicalRecordInput): Promise<MedicalRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.createMedicalRecord(to_candid_MedicalRecordInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MedicalRecord_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMedicalRecord(to_candid_MedicalRecordInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MedicalRecord_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMedicalRecord(arg0: RecordId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicalRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicalRecord(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<ProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRecord(arg0: RecordId): Promise<MedicalRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRecord(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRecord(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyRecords(): Promise<Array<MedicalRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyRecords();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyRecords();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertMyProfile(arg0: ProfileInput): Promise<ProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMyProfile(arg0);
            return result;
        }
    }
}
function from_candid_FileType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileType): FileType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MedicalRecord_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicalRecord): MedicalRecord {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileView]): ProfileView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MedicalRecord]): MedicalRecord | null {
    return value.length === 0 ? null : from_candid_MedicalRecord_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    visitDate: string;
    fileName: string;
    fileSize: bigint;
    fileType: _FileType;
    notes: [] | [string];
    hospitalName: string;
    doctorName: string;
    uploadedAt: _Timestamp;
    fileKey: string;
}): {
    id: RecordId;
    visitDate: string;
    fileName: string;
    fileSize: bigint;
    fileType: FileType;
    notes?: string;
    hospitalName: string;
    doctorName: string;
    uploadedAt: Timestamp;
    fileKey: string;
} {
    return {
        id: value.id,
        visitDate: value.visitDate,
        fileName: value.fileName,
        fileSize: value.fileSize,
        fileType: from_candid_FileType_n7(_uploadFile, _downloadFile, value.fileType),
        notes: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.notes)),
        hospitalName: value.hospitalName,
        doctorName: value.doctorName,
        uploadedAt: value.uploadedAt,
        fileKey: value.fileKey
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Insurance: null;
} | {
    TestReport: null;
} | {
    Xray: null;
} | {
    DoctorNote: null;
} | {
    Other: null;
} | {
    Prescription: null;
}): FileType {
    return "Insurance" in value ? FileType.Insurance : "TestReport" in value ? FileType.TestReport : "Xray" in value ? FileType.Xray : "DoctorNote" in value ? FileType.DoctorNote : "Other" in value ? FileType.Other : "Prescription" in value ? FileType.Prescription : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MedicalRecord>): Array<MedicalRecord> {
    return value.map((x)=>from_candid_MedicalRecord_n5(_uploadFile, _downloadFile, x));
}
function to_candid_FileType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): _FileType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MedicalRecordInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicalRecordInput): _MedicalRecordInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visitDate: string;
    fileName: string;
    fileSize: bigint;
    fileType: FileType;
    notes?: string;
    hospitalName: string;
    doctorName: string;
    fileKey: string;
}): {
    visitDate: string;
    fileName: string;
    fileSize: bigint;
    fileType: _FileType;
    notes: [] | [string];
    hospitalName: string;
    doctorName: string;
    fileKey: string;
} {
    return {
        visitDate: value.visitDate,
        fileName: value.fileName,
        fileSize: value.fileSize,
        fileType: to_candid_FileType_n3(_uploadFile, _downloadFile, value.fileType),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        hospitalName: value.hospitalName,
        doctorName: value.doctorName,
        fileKey: value.fileKey
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): {
    Insurance: null;
} | {
    TestReport: null;
} | {
    Xray: null;
} | {
    DoctorNote: null;
} | {
    Other: null;
} | {
    Prescription: null;
} {
    return value == FileType.Insurance ? {
        Insurance: null
    } : value == FileType.TestReport ? {
        TestReport: null
    } : value == FileType.Xray ? {
        Xray: null
    } : value == FileType.DoctorNote ? {
        DoctorNote: null
    } : value == FileType.Other ? {
        Other: null
    } : value == FileType.Prescription ? {
        Prescription: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
